### ISSUE TITLE
使用JSAPI出现获取openid失败

### ISSUE THREAD

**Issue by lee853761** [dedemao/weixinPay#13]
不知道什么原因，调用jsapi页面出现获取openid失败

**Comment by lee853761** [comment]
使用native支付则显示parse xml error 。前段时间还好好的，突然就这样了，不知是哪里出现了问题

**Comment by dedemao** [comment]
估计你修改过密钥

**Comment by vince-x** [comment]
同样的问题，调试php发现，通过url 获取openid返回值是空。
还在继续调试。

**Comment by dedemao** [comment]
经测试，未出现该问题，可以在jsapi.php第113行下，打印$res这个变量看看返回结果是什么来调试下

**Comment by vince-x** [comment]
后续：
centos 6下curl访问https出错，现在测试，没有问题，我觉得可以close了。
