### ISSUE TITLE
你好，我设置了回调接口，但支付完成后没反应？

### ISSUE THREAD

**Issue by BecksWang** [dedemao/weixinPay#23]
如题，请问我应该怎么解决呢？商户平台也配置了 路径没问题我单独访问过

**Comment by dedemao** [comment]
你下载的是哪个demo呢

**Comment by LeoRoll** [comment]
我下载的
![image](https://user-images.githubusercontent.com/21209623/78138699-f2a48100-7459-11ea-8017-6cc9e2f08a0c.png)
拿到这2个文件，封装进类，再控制器中调用，设置好了回调地址，在回调方法里 Log::info 一下，支付成功后发现日志里没相关信息，也就是没进回调接口

**Comment by Coinsen** [comment]
出现同样问题，最后怎么解决的？

**Comment by dedemao** [comment]
你可以记录将回调信息记录在日志里，打开看看。有可能是API密钥不对，重置下API密钥试试。
