### ISSUE TITLE
支付方法里，元转换分不应该使用intval，这样精度有问题

### ISSUE THREAD

**Issue by xianrenqh** [dedemao/weixinPay#26]
支付方法里，元转换分不应该使用intval，这样精度有问题。
比如支付19.9元，实际唤起的支付金额为19.89元。
可以使用bcmul()函数
源代码：
$unified = array(
            'appid' => $config['appid'],
            'attach' => 'pay',             //商家数据包，原样返回，如果填写中文，请注意转换为utf-8
            'body' => $orderName,
            'mch_id' => $config['mch_id'],
            'nonce_str' => self::createNonceStr(),
            'notify_url' => $notifyUrl,
            'openid' => $openid,            //rade_type=JSAPI，此参数必传
            'out_trade_no' => $outTradeNo,
            'spbill_create_ip' => '127.0.0.1',
            'total_fee' => intval($totalFee * 100),       //单位 转为分
            'trade_type' => 'JSAPI',
        );

修改代码：
$unified = array(
            'appid' => $config['appid'],
            'attach' => 'pay',             //商家数据包，原样返回，如果填写中文，请注意转换为utf-8
            'body' => $orderName,
            'mch_id' => $config['mch_id'],
            'nonce_str' => self::createNonceStr(),
            'notify_url' => $notifyUrl,
            'openid' => $openid,            //rade_type=JSAPI，此参数必传
            'out_trade_no' => $outTradeNo,
            'spbill_create_ip' => '127.0.0.1',
            'total_fee' => bcmul($totalFee,100),       //单位 转为分
            'trade_type' => 'JSAPI',
        );

**Comment by dedemao** [comment]
感谢反馈bug，但bcmul函数需要安装bcmath扩展才能使用，有的用户并没有安装这个扩展，提高了代码的使用难度。可通过`floatval($totalFee) * 100`来替代。
