### ISSUE TITLE
微信 V3 的异步回调失败的代码存在问题

### ISSUE THREAD

**Issue by swling** [dedemao/weixinPay#31]
微信判断 V3 的异步回调是否成功的标准，主要是依据 HTTP 状态码，而非响应内容。经过测试，无论响应什么内容，只要状态码是 200 都会被判定为成功，不再发送后续请求。我就此联系了微信人工客服，得到了确认。因此在 notify_v3.php 中对验签失败或业务处理失败的响应，需要修改。
[官方文档](https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_1_5.shtml) 底部
最后不得不吐槽，微信的官方文档真是稀碎啊

**Comment by dedemao** [comment]
的确，在处理失败时，应添加http_response_code函数来发送指定的状态码。
