### ISSUE TITLE
这个是不是精简了很多代码

### ISSUE THREAD

**Issue by cantinzing** [dedemao/weixinPay#5]
那个native扫码支付回调那个 notify.php怎么没有Queryorder这个方法 就是校验transaction_id那个

**Comment by dedemao** [comment]
只验证了签名，其余的你可以自己添加。

**Comment by cantinzing** [comment]
@dedemao 好吧

**Comment by ScriptElite** [comment]
unsubscribe

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："dedemao "<notifications@github.com&gt;;
发送时间：2020年8月5日(星期三) 下午2:56
收件人："dedemao/weixinPay" <weixinPay@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：Re: [dedemao/weixinPay] 这个是不是精简了很多代码 (#5)
-----------------------------------

 

 
Closed #5.
