### ISSUE TITLE
企业付款到零钱你试过吗大哥 看到请回答 我用了报错

### ISSUE THREAD

**Issue by guoqicai** [dedemao/weixinPay#7]
企业付款到零钱你试过吗大哥 看到请回答 我用了报错  邮箱897935247@qq.com

**Comment by xxhdxh** [comment]
现金红包没毛病已测试

**Comment by dedemao** [comment]
企业付款已测试，没毛病。如果提示PARAM ERROR，请检查文件是否是UTF-8格式。
