### ISSUE TITLE
请问下支付成功后没有回调呢？

### ISSUE THREAD

**Issue by wangerwazi** [dedemao/weixinPay#9]
把回调地址配置了，是不是支付成功后会跳转到配置的那个地址呢？

**Comment by dedemao** [comment]
回调是异步的，不可见的。

**Comment by wangerwazi** [comment]
那我该怎样看到支付成功后的信息呢？现在直接打开回调的网址显示的是parse xml error 是成功后微信会给我配置的网址发消息吗？我是前端，对PHP不是很熟悉。

**Comment by dedemao** [comment]
对，微信服务器会推送消息到你配置的网址。你估计想要的是这个效果：https://www.dedemao.com/wx/native2.php

**Comment by BecksWang** [comment]
> 对，微信服务器会推送消息到你配置的网址。你估计想要的是这个效果：https://www.dedemao.com/wx/native2.php

请问一下这种效果怎么实现呢

**Comment by dedemao** [comment]
你可以下载这个文件看下代码
